from collections import Counter

from sqlalchemy import String, cast, or_, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session, selectinload

from app.models.billing import Bill
from app.models.patient import Patient
from app.models.pharmacy import InventoryActionType, InventoryLog, Medicine, MedicineSale, MedicineSaleItem
from app.schemas.pharmacy import InventoryLogCreate, MedicineCreate, MedicineSaleCreate, MedicineUpdate


LOW_STOCK_THRESHOLD = 10


def generate_medicine_code(db: Session, offset: int = 1) -> str:
    latest_id = db.scalar(select(Medicine.id).order_by(Medicine.id.desc()).limit(1)) or 0
    return f"MED-{latest_id + offset:06d}"


def get_medicine(db: Session, medicine_id: int) -> Medicine | None:
    return db.get(Medicine, medicine_id)


def get_medicine_for_update(db: Session, medicine_id: int) -> Medicine | None:
    return db.scalar(select(Medicine).where(Medicine.id == medicine_id).with_for_update())


def find_medicine_by_code(db: Session, medicine_code: str | None, exclude_id: int | None = None) -> Medicine | None:
    if not medicine_code:
        return None
    query = select(Medicine).where(Medicine.medicine_code == medicine_code)
    if exclude_id is not None:
        query = query.where(Medicine.id != exclude_id)
    return db.scalar(query)


def list_medicines(db: Session, skip: int = 0, limit: int = 100, search: str | None = None) -> list[Medicine]:
    query = select(Medicine)
    if search:
        search_term = f"%{search.strip()}%"
        query = query.where(
            or_(
                Medicine.medicine_code.ilike(search_term),
                Medicine.medicine_name.ilike(search_term),
                Medicine.category.ilike(search_term),
                Medicine.manufacturer.ilike(search_term),
                cast(Medicine.stock_quantity, String).ilike(search_term),
            )
        )
    return list(db.scalars(query.order_by(Medicine.created_at.desc()).offset(skip).limit(limit)))


def create_medicine(db: Session, data: MedicineCreate) -> Medicine:
    payload = data.model_dump()
    autogenerated_code = not payload.get("medicine_code")

    for attempt in range(1, 6):
        if autogenerated_code:
            payload["medicine_code"] = generate_medicine_code(db, offset=attempt)

        medicine = Medicine(**payload)
        db.add(medicine)
        try:
            db.flush()
            if medicine.stock_quantity:
                db.add(InventoryLog(
                    medicine_id=medicine.id,
                    action_type=InventoryActionType.stock_in,
                    quantity=medicine.stock_quantity,
                    remarks="Opening stock",
                ))
            db.commit()
            db.refresh(medicine)
            return medicine
        except IntegrityError as exc:
            db.rollback()
            if not autogenerated_code:
                raise ValueError("Medicine code already exists") from exc

    raise ValueError("Could not generate a unique medicine code")


def update_medicine(db: Session, medicine: Medicine, data: MedicineUpdate) -> Medicine:
    payload = data.model_dump(exclude_unset=True)
    old_quantity = medicine.stock_quantity
    for field, value in payload.items():
        setattr(medicine, field, value)
    if "stock_quantity" in payload and payload["stock_quantity"] != old_quantity:
        difference = payload["stock_quantity"] - old_quantity
        db.add(InventoryLog(
            medicine_id=medicine.id,
            action_type=InventoryActionType.adjustment,
            quantity=abs(difference),
            remarks=f"Stock adjusted from {old_quantity} to {payload['stock_quantity']}",
        ))
    try:
        db.commit()
        db.refresh(medicine)
        return medicine
    except IntegrityError as exc:
        db.rollback()
        raise ValueError("Medicine code already exists") from exc


def delete_medicine(db: Session, medicine: Medicine) -> None:
    db.delete(medicine)
    db.commit()


def get_patient(db: Session, patient_id: int) -> Patient | None:
    return db.get(Patient, patient_id)


def get_bill(db: Session, bill_id: int) -> Bill | None:
    return db.get(Bill, bill_id)


def create_sale(db: Session, data: MedicineSaleCreate) -> MedicineSale:
    try:
        medicine_ids = {item.medicine_id for item in data.items}
        medicines = {
            medicine.id: medicine
            for medicine in db.scalars(
                select(Medicine)
                .where(Medicine.id.in_(medicine_ids))
                .with_for_update()
            )
        }
        missing_ids = medicine_ids - medicines.keys()
        if missing_ids:
            missing_list = ", ".join(str(medicine_id) for medicine_id in sorted(missing_ids))
            raise ValueError(f"Medicine not found: {missing_list}")

        requested_quantities = Counter()
        for item in data.items:
            requested_quantities[item.medicine_id] += item.quantity
        for medicine_id, requested_quantity in requested_quantities.items():
            medicine = medicines[medicine_id]
            if medicine.stock_quantity < requested_quantity:
                raise ValueError(f"Insufficient stock for {medicine.medicine_name}")

        sale = MedicineSale(
            patient_id=data.patient_id,
            bill_id=data.bill_id,
            payment_status=data.payment_status,
            total_amount=0,
        )
        db.add(sale)
        db.flush()

        total_amount = 0
        for item_data in data.items:
            medicine = medicines[item_data.medicine_id]
            unit_price = item_data.unit_price if item_data.unit_price is not None else medicine.unit_price
            total_price = unit_price * item_data.quantity
            medicine.stock_quantity -= item_data.quantity
            total_amount += total_price
            db.add(MedicineSaleItem(
                sale_id=sale.id,
                medicine_id=medicine.id,
                quantity=item_data.quantity,
                unit_price=unit_price,
                total_price=total_price,
            ))
            db.add(InventoryLog(
                medicine_id=medicine.id,
                action_type=InventoryActionType.sale,
                quantity=item_data.quantity,
                remarks=f"Medicine sale #{sale.id}",
            ))

        sale.total_amount = total_amount
        db.commit()
        db.refresh(sale)
        return sale
    except Exception:
        db.rollback()
        raise


def get_sale(db: Session, sale_id: int) -> MedicineSale | None:
    return db.scalar(select(MedicineSale).options(selectinload(MedicineSale.items)).where(MedicineSale.id == sale_id))


def list_sales(db: Session, skip: int = 0, limit: int = 100) -> list[MedicineSale]:
    query = select(MedicineSale).options(selectinload(MedicineSale.items)).order_by(MedicineSale.created_at.desc())
    return list(db.scalars(query.offset(skip).limit(limit)))


def list_inventory_logs(db: Session, skip: int = 0, limit: int = 100) -> list[InventoryLog]:
    return list(db.scalars(select(InventoryLog).order_by(InventoryLog.created_at.desc()).offset(skip).limit(limit)))


def list_low_stock(db: Session, threshold: int = LOW_STOCK_THRESHOLD) -> list[Medicine]:
    return list(db.scalars(select(Medicine).where(Medicine.stock_quantity <= threshold).order_by(Medicine.stock_quantity.asc())))


def create_inventory_log(db: Session, data: InventoryLogCreate) -> InventoryLog:
    try:
        medicine = get_medicine_for_update(db, data.medicine_id)
        if medicine is None:
            raise ValueError("Medicine not found")
        if data.action_type == InventoryActionType.stock_in:
            medicine.stock_quantity += data.quantity
        elif data.action_type in {InventoryActionType.stock_out, InventoryActionType.sale}:
            if medicine.stock_quantity < data.quantity:
                raise ValueError("Insufficient stock")
            medicine.stock_quantity -= data.quantity
        log = InventoryLog(**data.model_dump())
        db.add(log)
        db.commit()
        db.refresh(log)
        return log
    except Exception:
        db.rollback()
        raise
